### ISSUE TITLE
Simple big buttons

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Screen-ArkoPong-Back#1]
Сейчас в тестовом режиме на странице для мобильного используются две кнопки, и обрабатывается их нажатие.

Необходимо поменять эти кнопки на два блока по пол страницы, которые выполняют аналогичный функционал.

Необходимо сейчас сделать минимально рабочую страницу, для дальнейшей передачи работы в дизайн. 

Сейчас данный сервис доступен по адресу http://arkopong.screen.rtuitlab.dev/

Вся верстка находится в файле https://github.com/RTUITLab/Screen-ArkoPong-Back/blob/master/arkopongBack/wwwroot/index.html

**Comment by D0rG** [comment]
Сейчас на телефоне не играбельно.

**Comment by IvLaptev** [comment]
@D0rG, в чём заключается "не играбельно"?

**Comment by D0rG** [comment]
@IvLaptev, кнопку зажать не получается, и если нажимать то просто картинку скейлит.
Тестил в сафари

**Comment by IvLaptev** [comment]
@D0rG, попробуй ещё раз. Кажется пофиксил.

**Comment by D0rG** [comment]
@IvLaptev, ну теперь работает, правда иногда не с первого раза реагирует и на серваке пролетает два ноля

**Comment by IvLaptev** [comment]
Можешь описать ситуации, при которых появляются ошибки?

Довольно долго поиграл, но два раза ноль не получал. Играл одним игроком.

То, что не сразу реагирует, может быть связано с тем, что ты нажимаешь, не успев оторвать палец от второй кнопки.

**Comment by CAPCHIK** [comment]
Простой способ вызова ошибки - открыть сайт по QR коду и обновить страницу. Приложение сразу же вылетает.

**Comment by D0rG** [comment]
Погоди, @CAPCHIK, это не ошибка. Это было сделано мной специально.

**Comment by CAPCHIK** [comment]
Так или иначе этот Issue про создание двух кнопок, чтобы можно было играть.
Я считаю, что кнопки есть, и на ТВ уже можно разворачивать и пробовать играть.

Далее все вопросы можно обсуждать в новых Issue.
