### ISSUE TITLE
Rename buttons text

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Screen-ArkoPong-Back#2]
Возможно пока нет дизайна под джойстик стоит сделать на кнопках текст "вверх" и "вниз", или две стрелки нарисовать на правой и левой кнопке.

"Лево" и "Право" малость ничего не объясняют.

**Comment by D0rG** [comment]
никаких кнопок, нужен ДЖОЙСТИК @IvLaptev

**Comment by CAPCHIK** [comment]
Для джойстика делается дизайн от @RTUITLab/designers

Мне кажется сейчас, быстро, поменять текст.

**Comment by D0rG** [comment]
@CAPCHIK текст я уже поменял [тут](https://github.com/RTUITLab/Screen-ArkoPong-Back/tree/02830f58564de57baebe40debbf90ea3a4bcf693), но пока не сливаю в мастер, а то телик упадет скорее всего, надо там обновить игру. Но я не на месте.

**Comment by CAPCHIK** [comment]
@D0rG  Если ты просто обновил названия кнопок - ничего не должно упасть, раз ты не менял логику остальную.

**Comment by D0rG** [comment]
@CAPCHIK я и подключение менял, теперь как ты и просил

**Comment by IvLaptev** [comment]
А дезигнерз знают, что нужна кнопка disconnect?

**Comment by D0rG** [comment]
Я вот не уверен что она нужна, можно же просто вкладку закрыть. Так что думаю и без неё можно обойтись, да и я там выпилил кое что (:

**Comment by D0rG** [comment]
@IvLaptev а так хотелось рычаг ):
