### ISSUE TITLE
Reload page error

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Screen-ArkoPong-Back#3]
Если открывать страницу по генерируемому QR коду и обновить её  - приложение вылетает. (закрывается?)

Такое поведение как минимум не предсказуемо. Если говорим про потерю соединения на телефоне, например, получается приложение на ТВ каким-то образом начинает зависеть от интернета на телефоне игрока.

Нужен комментарий @D0rG

**Comment by D0rG** [comment]
Когда я это делал, таймера ещё не было, и оно изначально было сделано для выключения игры когда выходит один из игроков, ибо какой-то конечной точки игры нет

**Comment by CAPCHIK** [comment]
Учитывая, что теперь есть таймер - выход одного из игроков не должен ронять приложение уж точно.

Это не логичное поведение приложения, и при отключении клиента можно пытаться его присоединить снова, при этом ставив игру на паузу, например.

Либо, если не ронять приложение - то выводить сообщение про то, что так-то, игрок был отключен, запускайтесь заново.

**Comment by D0rG** [comment]
Ок, сделаю, наверно, переподключение

**Comment by D0rG** [comment]
@CAPCHIK А если не делать кнопку отключения на клиенте, а просто отрубать игру, если два человека отключились от сервера? То есть если ливнёт только один игрок, то игра приостановится и будет ждать переподключение, а если ливнёт и другой, то игра упадет.

**Comment by CAPCHIK** [comment]
@D0rG Я предлагаю сделать так 

Если кто-то отключается - есть 10 секунд на то чтобы переподключиться, и это необходимо показывать на ТВ

При этом можно на клиенте именно обновить вкладку спокойно, ибо почему нет

Так, например, у меня вкладка после qr кода открывается в встроенном браузере гугл камеры, а чтобы открыть нормально получается надо её перноткрыть самостоятельно

Соответственно, как только кто-то один отрубился - есть 10 секунд на переподклбчение, если так и не вышло - роняешь игру со словами "ну и все, ребятки"

**Comment by D0rG** [comment]
@CAPCHIK, слушай, а я могу не делать отображение таймера, пока висит ожидание. А то мне пришлось останавливать физику во время ожидания, а с ней и таймер падает. А из другого треда не зя дергать за UI мой. Ибо костылять как то не хочется с метиорами.

НЕ актуально.
